# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: rikorose/gcc-cmake:latest
#image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          # Install wget
          #- apt-get update -qq
          #- apt-get install wget -y --force-yes
          # Install CMake 3.7.1
          #- wget -O cmake.sh https://cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.sh
          #- chmod +x cmake.sh
          #- sh cmake.sh
          # Do a update again
          #- apt-get update
          # Print the CMake version.
          - cmake --version          
          - mkdir build
          - cd build
          # Call the CMake.
          - cmake ..
          # Build the porject.
          - make