#set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake")

set(CHESS_ANN_BENCHMARK_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/benchmark/include")
set(CHESS_ANN_CATCH_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/Catch/include")
set(CHESS_ANN_FANN_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/fann/include")
set(CHESS_ANN_UCI_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/external/uci/include")

set(CHESS_ANN_ENGINE_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src/include")
set(CHESS_ANN_ENGINE_PROJECT_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")
